#!/usr/bin/env bash
# This script installs nginx on ubuntu server

sudo apt-get update

sudo apt-get install nginx -y
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        return 200 "Hello World!\n";
    }
}
EOF

sudo service nginx restart
