#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get install nginx -y
echo "<!DOCTYPE html><html><head><title>404 Not Found</title></head><body><h1>404 Not Found</h1><p>Ceci n'est pas une page</p></body></html>" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i 's|#error_page 404 /404.html;|error_page 404 /404.html;|' /etc/nginx/sites-enabled/default
sudo service nginx restart
