#!/usr/bin/env bash
#A script that displays a list of currrently running processes.
#	Must show all processes, for all users, including those which might not have TTY
# 	Display in a user-oriented format
# 	Show process hierarchy

ps -auxf
