#!/usr/bin/env bash
# A script that displays Best School 10 times and hi after the 9th using while and if

count=1
while [ $count -le 10 ]
do
    if [ $count -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    count=$((count+1))
done