#!/usr/bin/env bash
#A script that used as an IP set up for working in docker

cp /etc/hosts ~/hosts.new
echo -e "127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com" > ~/hosts.new
cp -f ~/hosts.new /etc/hosts
